spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET:}
spring.security.oauth2.client.registration.google.scope=openid,profile,email

server.port=8081

app.frontend-url=http://localhost:5173

spring.datasource.url=jdbc:postgresql://localhost:5432/smart_campus_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
